#!/bin/sh

# e.g. for 100 iters
# fuzz/run 100 rng quick 5 5

node_modules/typescript/bin/tsc --project fuzz/tsconfig.json

iterations=$1
echo "looping $iterations times"

i=1
while [ $i -le $iterations ]
do
    node fuzz/out/fuzz/entry.js "$2" "$3" "$4" "$5"
    i=$((i+1))
done
